### ISSUE TITLE
Having trouble connecting

### ISSUE THREAD

**Issue by edin-m** [wdavidw/node-ssh2-connect#2]
Hi.

I get:

```
{ [Error: All configured authentication methods failed] level: 'client-authentication' } undefined

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:147:15)
    at SSH2Stream.Readable.push (_stream_readable.js:128:10)
    at SSH2Stream.Transform.push [as __push] (_stream_transform.js:140:32)
    at SSH2Stream.push (/home/emujagic/vft/exp/sshnode/node-ssh2-connect/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:217:18)
```

when trying to use it. I am not sure if I am using correctly but when I create ssh2 only connection it works.

```
var connect = require('ssh2-connect');
var opts = { 
    username: 'vagrant', 
    host: '127.0.0.1', 
    port: 2200, 
    privateKey: fs.readFileSync('./key')
};

//var conn = new ssh2();
//conn.on('err', console.error.bind(console, 'error'));
//conn.on('ready', console.log.bind(console, 'ready'));
//conn.connect(opts);

connect(opts, function(err, ssh) {
    console.log(err, ssh);
});
```

I have this issue with git clone as well with npm version.
Commented part works fine. Is this an issue or am I using it wrong?

**Comment by wdavidw** [comment]
That's pretty much what we do internally:

``` coffee
connection = new ssh2()
connection.on 'error', (err) ->
  connection.end()
  # Event "error" is thrown after a "ready" if the connection is lost
  return if succeed
  if retry is true or retry > 0
  then setTimeout connect, 2000
  else callback err
connection.on 'ready', ->
  succeed = true
  callback null, connection
connection.connect options
```

I cant see anything wrong

**Comment by edin-m** [comment]
Yeah, that's why this error is confusing to me. I was just wondering am I using ssh2-connect the way it's ment to be.

**Comment by wdavidw** [comment]
as far as I can tell, it looks correct to me.

**Comment by wdavidw** [comment]
i found the reason. the camelize module was altering the buffer you provided. thanks for reporting this, a new version is published.

**Comment by edin-m** [comment]
Thanks!
